name: Testing

on: push

jobs:
  test:
    name: Tests passes
    runs-on: ubuntu-latest

    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: Install modules
        run: npm ci

      - name: Testing
        run: npm test
        env:
          DEBUG: ${{ secrets.DEBUG }}
          MONGO_DB_URI: ${{ secrets.MONGO_DB_URI }}
          MONGO_DB_DEBUG: ${{ secrets.MONGO_DB_DEBUG }}
          ALLOWED_ORIGINS: ${{ secrets.ALLOWED_ORIGINS }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          TOKEN_EXPIRY: ${{ secrets.TOKEN_EXPIRY }}
          SALT_LENGTH: ${{ secrets.SALT_LENGTH }}
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
          SUPABASE_BUCKET: ${{ secrets.SUPABASE_BUCKET }}
